#  Import statements
import unittest  # Import Python package unittest (within Pythonpath)
import EBC_Tutorial.example_1 as exp  # Import example_1.py


class MyTestExample_1(unittest.TestCase):
    """
    I am a test class for example_1.py
    I am generated by inheritance from class unittest.TestCase
    """

    def test_positve_int(self):
        """
        Testing method for positive integer inputs
        """
        self.assertEqual(exp.square_int_number(2), 4)

    def test_zero(self):
        """
        Testing method for input zero
        """
        self.assertEqual(exp.square_int_number(0), 0)

    def test_negative_int(self):
        """
        Testing method for negative integer inputs
        """
        self.assertEqual(exp.square_int_number(-2), 4)


if __name__ == '__main__':
    #  Call unittest.main() and execute all
    #  testing methods of MyTestExampe_1
    unittest.main()
